ComicBook/ComicBook/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBook.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

ComicBook/ComicBook/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBook.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int IssueNumber { get; set; }
        public string Description { get; set; }
        public Artist[] Artists { get; set; }     
        public string DisplayText
        {
            get
            {
                return Title + " #" + IssueNumber;
            }
            //set   //Contoh doang
            //{
            //    DisplayText = blablabla;
            //}
        }

        public string CoverImageFileName
        {
            get
            {
                return Title.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
            }
        }
    }
}

ComicBook/ComicBook/Controllers/ComicBooksController.cs
using ComicBook.Data;
using ComicBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicBook.Controllers
{
    public class ComicBooksController : Controller //gunanya untuk menerima, memproses dan menampilkan data
    {
        private ComicBookRepository _comicBookRepository = new ComicBookRepository();

        public ActionResult Detail(int? id) //Harus public karena diakses di semua class, di kasih tanda tanya biar bisa ngakses null
        {
            if (id == null)
                return HttpNotFound();

            var selectedComicBook = _comicBookRepository.getComicBook((int)id);
            return View(selectedComicBook);

            /*
             * Dipindahin ke Repository
             */ 
            //var comicBook = new Models.ComicBook()
            //{
            //    Title = "The Amazing Spider-Man",
            //    IssueNumber = 700,
            //    Description = "<p>Final issue! Witness the final hours of Doctor Octopus' life and his one, last, " +
            //    "great act of revenge! Even if Spider-Man survives... <strong>will Peter Parker?</strong></p>",
            //    Artists = new Artist[]
            //    {
            //        new Artist {Name = "Dan Slott", Role = "Script"},
            //        new Artist {Name = "Humberto Ramos", Role = "Pencils"},
            //        new Artist {Name = "Victor Olazaba", Role = "Inks"},
            //        new Artist {Name = "Edgar Delgado", Role = "Colors"},
            //        new Artist {Name = "Chris Eliopoulos", Role = "Letters"}
            //    }
            //};
            //return View(comicBook);

            /*
             * AWALNYA GINI, Pake ViewBag untuk convert ke html nantinya
             * DIGANTI sama yang ATAS
             */
            //ViewBag.Title = "The Amazing Spider-Man";
            //ViewBag.issueNumber = 700;
            //ViewBag.description = "<p>Final issue! Witness the final hours of Doctor Octopus' life and his one, last, great act of revenge! Even if Spider-Man survives... <strong>will Peter Parker?</strong></p>";
            //ViewBag.artists = new string[]
            //{
            //    "Script: Dan Slott",
            //    "Pencils: Humberto Ramos",
            //    "Inks: Victor Olazaba",
            //    "Colors: Edgar Delgado",
            //    "Letters: Chris Eliopoulos"
            //}; 
            //return View(); //yang dipanggil Detail.cshtml
        }

        public ActionResult Index()
        {
            var allComicBook = _comicBookRepository.getAllComicBook();
            return View(allComicBook);
        }
    }
}

ComicBook/ComicBook/Views/ComicBooks/Detail.cshtml
@model ComicBook.Models.ComicBook

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.showBack = true;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @*OLD VERSION*@
        @*<h1>@Model.Title</h1>
        <h2>Issue: #@Model.IssueNumber</h2>

        <h5>Description:</h5>
        <div>@Html.Raw(Model.Description)</div>

        <h5>Artist:</h5>
        <h5>@foreach (var a in Model.Artists)
        {
            <ul>
                <li>@a.Role : @a.Name;</li>
            </ul>            
        }
        </h5>*@


        @*NEW VERSION*@
        <h2>@Model.Title #@Model.IssueNumber</h2>

        <div class="row">
            <div class="col-md-6">
                <div class="well">
                    <h5><label>Series Title:</label> @Model.Title</h5>
                    <h5><label>Issue #:</label> @Model.IssueNumber</h5>
                    <h5><label>Favorite:</label> Yes</h5>
                    <h5>Artists:</h5>
                    <div>                        
                        <ul>
                            @foreach (var a in Model.Artists)
                            {
                               <li>@a.Role : @a.Name;</li>
                            }
                        </ul>                        
                    </div>
                </div>
                <h5>Description</h5>
                @Html.Raw(Model.Description)
            </div>
            <div class="col-md-6">
                <img src="/Images/@Model.CoverImageFileName" alt="@Model.DisplayText" class="img-responsive" />
            </div>
        </div>
    </div>
</body>
</html>

ComicBook/ComicBook/Views/ComicBooks/Index.cshtml
@*m harus kecil, supaya muncul intelisense dari semua pemanggilan class, method di model*@
@model ComicBook.Models.ComicBook[]

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row">
    @foreach (var comic in Model)
    {
        <div class="col-md-3">
            <a href="@Url.Action("Detail", new { id = comic.Id })">
                <h4>@comic.DisplayText</h4>
                @*<h4>@Html.ActionLink(comic.DisplayText, "Detail", new { id = comic.Id })</h4>*@
                <img src="/Images/@comic.CoverImageFileName"
                     alt="@comic.DisplayText"
                     class="img-responsive" />
            </a>
        </div>
    }
    
</div>

ComicBook/ComicBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })
            </div>           
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>

    @if (ViewBag.showBack == true)
    {
        <div class="backbar">
            <div class="container">
                @*<a class="btn btn-default" href="/">Return to List</a>*@
                @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    }    

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>